services:
  aes-ascon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aes-ascon-benchmark
    restart: "no"
    volumes:
      - ./results:/results
    command: ["./run-aes-ascon.sh"]

  json-cbor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: json-cbor-benchmark
    restart: "no"
    volumes:
      - ./results:/results
    command: ["./run-json-cbor.sh"]
