services:
  aes-ascon-with-acceleration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aes-ascon-with-acceleration-benchmark
    restart: "no"
    tty: true
    env_file:
      - ./config/benchmark.env
    volumes:
      - ./results:/results
    command: ["./run-aes-ascon-with-acceleration.sh"]

  aes-ascon-without-acceleration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aes-ascon-without-acceleration-benchmark
    restart: "no"
    tty: true
    env_file:
      - ./config/benchmark.env
    volumes:
      - ./results:/results
    command: ["./run-aes-ascon-without-acceleration.sh"]

  json-cbor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: json-cbor-benchmark
    restart: "no"
    tty: true
    env_file:
      - ./config/benchmark.env
    volumes:
      - ./results:/results
    command: ["./run-json-cbor.sh"]

  payload-scaling:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payload-scaling-benchmark
    restart: "no"
    tty: true
    env_file:
      - ./config/benchmark.env
    volumes:
      - ./results:/results
    command: ["./run-payload-scaling.sh"]

  attribute-key-scaling:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attribute-key-scaling-benchmark
    restart: "no"
    tty: true
    env_file:
      - ./config/benchmark.env
    volumes:
      - ./results:/results
    command: ["./run-attribute-key-scaling.sh"]
