listener 8883

allow_anonymous false
password_file /mosquitto/config/passwords
acl_file /mosquitto/config/acl

certfile /mosquitto/config/certs/broker.crt
keyfile /mosquitto/config/certs/broker.key

tls_version tlsv1.3
require_certificate false

persistence false
sys_interval 0

set_tcp_nodelay true

log_dest stdout