sonar.organization=kevinshemili
sonar.projectKey=KevinShemili_MQTT-Thesis
sonar.projectName=MQTT-Thesis

sonar.sourceEncoding=UTF-8
sonar.python.version=3.14

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go,**/test_*.py,**/*_test.py

sonar.exclusions=\
    .venv/**,\
    results/**,\
    benchmark/bin/**,\
    benchmark/disk-cache/**,\
    .scannerwork/**,\
    coverage-go.out,\
    coverage-python.xml,\
    report/template/**,\
    report/render/**,\
    broker/**,\
    benchmark/cpu/**,\
    benchmark/memory/**,\
    benchmark/thermal/**,\
    benchmark/micro/**,\
    utility/python/um24c/**,\
    .sonar/**,\
    **/__pycache__/**,\
    **/.pytest_cache/**

sonar.test.exclusions=\
    .venv/**,\
    results/**,\
    benchmark/bin/**,\
    benchmark/disk-cache/**,\
    .scannerwork/**,\
    report/template/**,\
    report/render/**,\
    broker/**,\
    benchmark/cpu/**,\
    benchmark/memory/**,\
    benchmark/thermal/**,\
    benchmark/micro/**,\
    um24c/**,\
    .sonar/**

sonar.coverage.exclusions=report/render/**

sonar.working.directory=.sonar/.scannerwork
sonar.go.coverage.reportPaths=.sonar/reports/coverage-go.out
sonar.python.coverage.reportPaths=.sonar/reports/coverage-python.xml

sonar.issue.ignore.multicriteria=s5443,s5443path,s7637,s8541,s8544

sonar.issue.ignore.multicriteria.s5443.ruleKey=python:S5443
sonar.issue.ignore.multicriteria.s5443.resourceKey=orchestrate/orchestrate_*.py

sonar.issue.ignore.multicriteria.s5443path.ruleKey=python:S5443
sonar.issue.ignore.multicriteria.s5443path.resourceKey=utility/python/path/path.py

sonar.issue.ignore.multicriteria.s8541.ruleKey=githubactions:S8541
sonar.issue.ignore.multicriteria.s8541.resourceKey=.github/workflows/ci.yml

sonar.issue.ignore.multicriteria.s8544.ruleKey=githubactions:S8544
sonar.issue.ignore.multicriteria.s8544.resourceKey=.github/workflows/ci.yml

sonar.issue.ignore.multicriteria.s7637.ruleKey=githubactions:S7637
sonar.issue.ignore.multicriteria.s7637.resourceKey=.github/workflows/ci.yml