services:
  aes-ascon:
    build:
      context: ../..
      dockerfile: orchestrate/laptop/Dockerfile
    container_name: aes-ascon-benchmark
    restart: "no"
    tty: true
    working_dir: /app
    volumes:
      - ../../results:/app/results
    command: ["python3", "orchestrate/raspberry/orchestrate_aes_ascon.py"]

  json-cbor:
    build:
      context: ../..
      dockerfile: orchestrate/laptop/Dockerfile
    container_name: json-cbor-benchmark
    restart: "no"
    tty: true
    working_dir: /app
    volumes:
      - ../../results:/app/results
    command: ["python3", "orchestrate/raspberry/orchestrate_json_cbor.py"]

  full-schema:
    build:
      context: ../..
      dockerfile: orchestrate/laptop/Dockerfile
    container_name: full-schema-benchmark
    restart: "no"
    tty: true
    working_dir: /app
    volumes:
      - ../../results:/app/results
    command: ["python3", "orchestrate/raspberry/orchestrate_full_schema.py"]

  cpabe-rsa:
    build:
      context: ../..
      dockerfile: orchestrate/laptop/Dockerfile
    container_name: cpabe-rsa-benchmark
    restart: "no"
    tty: true
    working_dir: /app
    volumes:
      - ../../results:/app/results
    command:
      ["python3", "orchestrate/raspberry/orchestrate_cpabe_rsa.py"]
