services:
  aes-ascon:
    build:
      context: ../..
      dockerfile: orchestrate/laptop/Dockerfile
    container_name: aes-ascon-benchmark
    restart: "no"
    tty: true
    working_dir: /app
    volumes:
      - ../../results:/app/results
    command: ["python3", "orchestrate/raspberry/orchestrate_aes_ascon.py"]

  json-cbor:
    build:
      context: ../..
      dockerfile: orchestrate/laptop/Dockerfile
    container_name: json-cbor-benchmark
    restart: "no"
    tty: true
    working_dir: /app
    volumes:
      - ../../results:/app/results
    command: ["python3", "orchestrate/raspberry/orchestrate_json_cbor.py"]

  payload-scaling:
    build:
      context: ../..
      dockerfile: orchestrate/laptop/Dockerfile
    container_name: payload-scaling-benchmark
    restart: "no"
    tty: true
    working_dir: /app
    volumes:
      - ../../results:/app/results
    command: ["python3", "orchestrate/raspberry/orchestrate_payload_scaling.py"]

  attribute-key-scaling:
    build:
      context: ../..
      dockerfile: orchestrate/laptop/Dockerfile
    container_name: attribute-key-scaling-benchmark
    restart: "no"
    tty: true
    working_dir: /app
    volumes:
      - ../../results:/app/results
    command:
      ["python3", "orchestrate/raspberry/orchestrate_attribute_key_scaling.py"]
