services:
  mosquitto:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: mqtt-thesis-broker

    ports:
      - "8883:8883"

    env_file:
      - ../environment/benchmark.env

    volumes:
      - broker-state:/state

    restart: "no"

volumes:
  broker-state:
