user mosquitto

listener 8883

allow_anonymous false

password_file /state/passwords
acl_file /mosquitto/config/acl

certfile /state/certs/broker.crt
keyfile /state/certs/broker.key

tls_version tlsv1.3
require_certificate false

persistence false
sys_interval 0

set_tcp_nodelay true

log_dest stdout